version: "3.7"
services:
    apache:
        build:
            context: ./
            dockerfile: Dockerfile
            args:
                user: essana3 # your username on your machine, you can get it by running echo $USER
                uid: 1000
        restart: always
        ports:
            - 80:80
        volumes:
            - ../:/var/www/html
            - ./vhost.conf:/etc/apache2/sites-enabled/000-default.conf
    db:
        container_name: laravel-mysql
        image: mysql:latest
        restart: always
        environment:
            MYSQL_DATABASE: laravel
            MYSQL_ROOT_PASSWORD: root
        volumes:
            - /db:/var/lib/mysql
        ports:
            - "3306:3306"
    phpmyadmin:
        depends_on:
            - db
        image: phpmyadmin/phpmyadmin
        container_name: phpmyadmin
        restart: always
        ports:
            - '8080:80'
        environment:
            PMA_HOST: db
